In [8]:
import yfinance as yf 
import pandas as pd
import numpy as np 
import smtplib
from email.mime.text import MIMEText

In [9]:
oil = yf.download("BZ=F", period="1y")
oil.head()

[*********************100%***********************]  1 of 1 completed

Price           Close       High        Low       Open Volume
Ticker           BZ=F       BZ=F       BZ=F       BZ=F   BZ=F
Date
2025-05-01  62.130001  62.360001  59.310001  61.139999  66984
2025-05-02  61.290001  62.720001  60.700001  61.880001  58444
2025-05-05  60.230000  60.770000  58.410000  59.509998  49504
2025-05-06  62.150002  62.799999  60.189999  60.279999  63444
2025-05-07  61.119999  63.209999  60.849998  62.070000  60579

In [10]:
oil2 = oil['Close']
oil2

Ticker            BZ=F
Date
2025-05-01   62.130001
2025-05-02   61.290001
2025-05-05   60.230000
2025-05-06   62.150002
2025-05-07   61.119999
...                ...
2026-04-27  108.230003
2026-04-28  111.260002
2026-04-29  118.029999
2026-04-30  114.010002
2026-05-01  111.160004

[253 rows x 1 columns]

In [11]:
df = oil2.copy()
df['rolling_40'] = oil2.rolling(40).mean()
df['rolling_90'] = oil2.rolling(90).mean()

df = df.dropna()

print(df)

Ticker            BZ=F  rolling_40  rolling_90
Date
2025-09-08   66.019997   68.130750   67.531555
2025-09-09   66.389999   68.060250   67.578889
2025-09-10   67.489998   68.029749   67.647778
2025-09-11   66.370003   67.976000   67.716000
2025-09-12   66.989998   67.912750   67.769778
...                ...         ...         ...
2026-04-27  108.230003   99.991000   80.940111
2026-04-28  111.260002  100.829000   81.521667
2026-04-29  118.029999  101.744750   82.170000
2026-04-30  114.010002  102.560000   82.772111
2026-05-01  111.160004  103.203750   83.335333

[164 rows x 3 columns]

In [12]:
df['signal'] = 0
df['signal'] = np.where(df['rolling_40'] > df['rolling_90'],
                         1,
                         -1
                         )
df['crossover'] = df['signal'].diff()
df = df.dropna()
df.tail()

Ticker            BZ=F  rolling_40  rolling_90  signal  crossover
Date
2026-04-27  108.230003    99.99100   80.940111       1        0.0
2026-04-28  111.260002   100.82900   81.521667       1        0.0
2026-04-29  118.029999   101.74475   82.170000       1        0.0
2026-04-30  114.010002   102.56000   82.772111       1        0.0
2026-05-01  111.160004   103.20375   83.335333       1        0.0

In [13]:
Last_Value = df.iloc[-1]
print(Last_Value)

Ticker
BZ=F          111.160004
rolling_40    103.203750
rolling_90     83.335333
signal          1.000000
crossover       0.000000
Name: 2026-05-01 00:00:00, dtype: float64

In [15]:
if Last_Value['crossover'] == 2:
    print("Positive increasing trend")
elif Last_Value['crossover'] == -2:
    print("Negative decreasing trend"),
else:
    print("Nessun crossover oggi")

Nessun crossover oggi